### ISSUE TITLE
[Bug] Blocks that use connected textures don't render in the inventory

### ISSUE THREAD

**Issue by TuczComics** [SuperMartijn642/Fusion#174]
Version Info
- Minecraft, 1.21.9
- Fusion 1.2.11

What mod loader are you using?: Fabric

Are you using OptiFine: no

Description of the Bug
When using a resource pack with the connected texture support, the block texture won't render in the inventory, instead just having a blank texture. This also occurs in your hand, in item frames, and when dropped on the ground.

Steps to Reproduce
1. Download any resource pack that uses Fusion connected textures
2. Use it in game
3. Select the block that uses connected textures and see that it doesn't render

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/a38e2083-b57d-4788-a797-99e6f2299993" />

**Comment by SuperMartijn642** [comment]
This is caused by Fabric API item rendering not working.
https://github.com/FabricMC/fabric/blob/9983246df433bf891dcff703fa9e303ca18cfbc1/fabric-renderer-indigo/src/client/java/net/fabricmc/fabric/mixin/client/indigo/renderer/ItemRenderStateLayerRenderStateMixin.java#L41

There is not much I can do about it. Just have to wait until Fabric API is updated.

**Comment by forditt** [comment]
fabric API updated

```
[1.21.9] Fabric API 0.134.0+1.21.9

Changelog
Bump version (modmuss50)
Improve fix for packet order (#4897) (modmuss)
Add ScreenEvents.AfterBackground event (#4880) (Fuzss)
Provide a way to get existing spawn entries in SpawnSettingsContext (#4884) (Fuzss)
Fix custom play payload packets not being handled on the correct thread. (#4896) (modmuss)
Fix missing mutable annotation in GameRuleRpcDispatcherTypedRuleMixin (modmuss50)
1.21.9 (modmuss50)
```

**Comment by SuperMartijn642** [comment]
https://github.com/FabricMC/fabric/issues/4900

**Comment by MiSosumi** [comment]
Glass does not even appear as a dropped item :(

**Comment by SuperMartijn642** [comment]
This has been fixed in Fabric API 0.135.0.

**Comment by giropita** [comment]
This bug still persists on Fabric 1.21.9/10 while using sodium 0.7.0.

**Comment by SuperMartijn642** [comment]
Sodium will likely copy it as well now that item rendering is implemented in Fabric API.
https://github.com/CaffeineMC/sodium/issues/3278
